//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.App.Client.EventService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EventService.EventServiceSoap")]
    public interface EventServiceSoap {
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateClaim", ReplyAction="*")]
        Demo.App.Client.EventService.UpdateClaimResponse UpdateClaim(Demo.App.Client.EventService.UpdateClaimRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateClaimRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateClaim", Namespace="http://tempuri.org/", Order=0)]
        public Demo.App.Client.EventService.UpdateClaimRequestBody Body;
        
        public UpdateClaimRequest() {
        }
        
        public UpdateClaimRequest(Demo.App.Client.EventService.UpdateClaimRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateClaimRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        public UpdateClaimRequestBody() {
        }
        
        public UpdateClaimRequestBody(int id, string name) {
            this.id = id;
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateClaimResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateClaimResponse", Namespace="http://tempuri.org/", Order=0)]
        public Demo.App.Client.EventService.UpdateClaimResponseBody Body;
        
        public UpdateClaimResponse() {
        }
        
        public UpdateClaimResponse(Demo.App.Client.EventService.UpdateClaimResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateClaimResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateClaimResult;
        
        public UpdateClaimResponseBody() {
        }
        
        public UpdateClaimResponseBody(string UpdateClaimResult) {
            this.UpdateClaimResult = UpdateClaimResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EventServiceSoapChannel : Demo.App.Client.EventService.EventServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EventServiceSoapClient : System.ServiceModel.ClientBase<Demo.App.Client.EventService.EventServiceSoap>, Demo.App.Client.EventService.EventServiceSoap {
        
        public EventServiceSoapClient() {
        }
        
        public EventServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EventServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EventServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EventServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.App.Client.EventService.UpdateClaimResponse Demo.App.Client.EventService.EventServiceSoap.UpdateClaim(Demo.App.Client.EventService.UpdateClaimRequest request) {
            return base.Channel.UpdateClaim(request);
        }
        
        public string UpdateClaim(int id, string name) {
            Demo.App.Client.EventService.UpdateClaimRequest inValue = new Demo.App.Client.EventService.UpdateClaimRequest();
            inValue.Body = new Demo.App.Client.EventService.UpdateClaimRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            Demo.App.Client.EventService.UpdateClaimResponse retVal = ((Demo.App.Client.EventService.EventServiceSoap)(this)).UpdateClaim(inValue);
            return retVal.Body.UpdateClaimResult;
        }
    }
}
